---
- hosts: undercloud
  vars:
    metadata: Check access to various openstack services
    description: >
      This will attempt to connect to each service endpoint defined in your hosts file's controller_vip variable.
      You must also set the appropriate credentials in validations/auth-header.json
  tasks:
  #Check connectivity to horizon
  - name: Check Horizon
    uri: url=http://{{controller_vip}} 

  #Check that we can obtain an auth token from horizon
  - name: Check Keystone
    uri: 
     url: http://{{controller_vip}}:5000/v2.0/tokens
     method: POST
     HEADER_Content-Type: "application/json"
     #to-do: come up with a better path mechanism to not hard-code paths
     body: "{{ ' ' + lookup('file','/home/stack/clapper/ansible-tests/validations/auth-header.json')}}"
     return_content: yes
    register: auth_token
#  - debug: var=auth_token

#to-do other endpoints
