---
- hosts: undercloud
  vars:
    metadata:
      name: Undercloud Services Debug Check
      description: >
        The undercloud's openstack services should _not_ have debug enabled.This will check if debug is enabled on undercloud services.  If debug is enabled, the root filesystem can fill up quickly, and is not a good thing.
      groups:
        - pre-deployment
    debug_check: "debug.*=.*True"
  tasks:
  - name: Check the services for debug flag
    become: true
    command: grep -i {{ debug_check }} {{ item }}
    register: grep_result
    with_items:
      - /etc/nova/nova.conf
      - /etc/neutron/neutron.conf
      - /etc/ceilometer/ceilometer.conf
      - /etc/heat/heat.conf
      - /etc/ironic/ironic.conf
    failed_when: "grep_result.rc != 1"
